version: '1.0'

services:
  webservice:
    container_name: "PHP-SERVER"
    build: ./build/php
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql-srv
  mysql-srv:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: stevenaurelemallo
      MYSQL_DATABASE: guild_db
      MYSQL_USER: steven
      MYSQL_PASSWORD: stevenaurelemallo
    ports:
      - "3306:3306"